# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Mo
subtitle:
SEOTitle: Mo's blog
description: "Mo's Blog at GitHub"
header-img: //s1.ax1x.com/2018/06/08/CHqLn0.jpg
keywords:
author: Marlous
language:
timezone:
email: Goonecat@foxmail.com
favicon: "/img/favicon.ico"

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://marlous.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# SNS settings
# RSS:
weibo_username: iapplestory
zhihu_username: Marlous
github_username: Marlous
twitter_username: MarlousMo
facebook_username:  
linkedin_username:

# friends
friends:  # 友链

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Extensions
## Plugins: https://hexo.io/plugins/

markdown:
  plugins:
    - markdown-it-abbr
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-sub
    - markdown-it-sup
    - markdown-it-emoji

# Sidebar settings
sidebar: true
sidebar-about-description: "My Conquest is the Sea of Stars."
sidebar-avatar: "/profile.JPG"

# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1             # A tag will be featured if the size of it is more than this condition value

# 博文默认图片(如果不设置这一项, 博文标题的图片默认是灰色的)
post-default-img: "/img/post-default-sky.jpg"

# archive page title 
archive:
    title: archives
    description: 可以根据归档日期检索所有文件
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date


# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: Anisina

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: git@github.com:Marlous/marlous.github.io.git
  branch: master

# 博文配置
# ---
# layout: post
# title: "Hola 2016"
# subtitle: "hi, I'm haojen ma"
# date: 2016-05-26 06:00
# author: "Haojen Ma"
# header-img: "/img/post-default.jpg"
# cdn: 'header-on'
# tags:
#   - Movies
#   - Life
# ---